In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [71]:
from collections import Counter
from sklearn.svm import SVC
import random
from sklearn.utils.validation import check_random_state
import numpy as np
from src.model import boosted_support_subset
from mlxtend.plotting import plot_decision_regions

In [16]:
idx = [i for i in range(100)]

In [36]:
ss_idx = []

In [37]:
ss_idx

[]

In [38]:
ss_index1 = [random.randint(0, len(idx)) for _ in range(15)]
ss_index2 = [random.randint(0, len(idx)) for _ in range(15)]

In [39]:
ss_index1

[35, 59, 52, 75, 61, 43, 31, 70, 52, 39, 31, 67, 94, 93, 84]

In [40]:
ss_idx.extend(ss_index1)

In [41]:
ss_idx

[35, 59, 52, 75, 61, 43, 31, 70, 52, 39, 31, 67, 94, 93, 84]

In [15]:
ss_index2

[92, 13, 40, 2, 47, 25, 3, 98, 2, 64, 30, 48, 63, 42, 97]

In [42]:
active_idx = list(set(idx) - set(ss_idx))

In [44]:
len(active_idx)

87

In [ ]:
random_instance.

In [50]:
for i in range(10):
    random_instance = check_random_state(1234 + i)
    sample_idx = random_instance.choice(active_idx, 20)
    print(sample_idx)

[51 96 41 58 87 24 15 54 23 26 30 47 30 26 65 79 91 83 51 55]
[86 36  2 77 81 37 60 16 16 55 76 90 20 89 41 44 71 90 11 32]
[37 86 92 28 63 90 62 34 83 62 19 99 80 68 64 60 28 50 18 38]
[11 42  7  0 34 83 87 92 15 64 98 10 82 88  0 12 18 90 74  6]
[78 71 18 82 66 44 86 21 97 41 63 72 56  4 53 30 51 30  2 50]
[ 0 27 78 77 79 30 46 56 82 42 56 74 90 90 91 81 68 17 81 16]
[51 33 13 62 37 29 77 15 40 45 40 17 20 85 25 38 91 51 33 77]
[64 63 86 14 69 68 12 63 91 90 77 78 32 86 74 10 26 32  9 46]
[90 53 47 73 76 91 60  3 97 92 76 15  9  5 65 95 65  1 19 83]
[56  3  7 29 54 46  8 74 29 83 88 29 91 40  9 58 17 37 89 88]


In [51]:
idx_learner = 0

In [52]:
 idx_learner += 1

In [54]:
idx_learner = 0
while True:
        
        idx_learner += 1
        if idx_learner > 10:
            break

In [72]:
pepe = Counter(np.hstack([np.ones(5), -1*np.ones(11)]))

In [84]:
sum([pepe[i] > 2 for i in pepe])

2

In [65]:
(Counter(np.hstack([np.ones(5), -1*np.ones(11)]))[0] > 2) & (Counter(np.hstack([np.ones(5), -1*np.ones(11)]))[1] > 2)

False

In [68]:
()[0]

0